### ISSUE TITLE
rGuiStyler v3.0 roadmap

### ISSUE THREAD

**Issue by raysan5** [raysan5/rguistyler#1]
List of required improvements for next version:

 - [x] Properly edit property value and text alignment.
 - [x] `ExportStyleAsCode()` review to allow a header-only code file implementing the style, this file could also contain the font as a data array (bit-map/grayscale).
 - [x] `GenImageStyleControlsTable()` review current implementation to avoid old `GenImageStylePalette()` and properly calculate controls grid width.
 - `ExportStyleInPNG()` implementation review and testing, make sure `rGSt` data chunck can be read and processed. *SKIPPED*
